name: Build Workflow
on: [ push, pull_request ]

jobs:
  build:
    name: Build (${{ matrix.config }})
    runs-on: windows-latest

    strategy:
      matrix:
        config: [ Debug, RelWithDebInfo ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Create environment variables
        run: |
          $commitSha = (git rev-parse --short $env:GITHUB_SHA)
          echo "RTTIDUMPER_COMMIT_SHA=${commitSha}" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append

          # CMake is building PDB files for release artifacts using "RelWithDebInfo" config.
          # Create a "pretty" name for this to make it easier to refer users to this CI artifact in case a bug needs
          # testing.
          $config = "${{ matrix.config }}"
          if ($config -eq "RelWithDebInfo") {
            $config = "release"
          }
          else {
            $config = $config.ToLower()
          }

          echo "RTTIDUMPER_PRETTY_CONFIG=${config}" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append

      - name: Create build directory
        run: mkdir build

      - name: Configure
        working-directory: build
        run: |
          cmake ${{ github.workspace }}

      - name: Build
        working-directory: build
        run: |
          cmake `
            --build . `
            --config ${{ matrix.config }}

      - name: Prepare ZIP
        working-directory: build
        run: |
          $packagingDir = "./.packaging"

          # Create the necessary directories.
          New-Item -ItemType directory -Path $packagingDir
          New-Item -ItemType directory -Path $packagingDir/red4ext
          New-Item -ItemType directory -Path $packagingDir/red4ext/plugins
          New-Item -ItemType directory -Path $packagingDir/red4ext/plugins/RED4ext.RTTIDumper

          # Copy the build artifacts.
          Copy-Item -Path ./${{ matrix.config }}/bin/RED4ext.RTTIDumper.dll -Destination $packagingDir/red4ext/plugins/RED4ext.RTTIDumper

          # Copy the license.
          Copy-Item -Path ../LICENSE.md -Destination $packagingDir/red4ext/plugins/RED4ext.RTTIDumper/LICENSE.txt

      - name: Prepare ZIP (PDBs)
        working-directory: build
        run: |
          $packagingDir = "./.packaging_pdbs"

          # Create the necessary directories.
          New-Item -ItemType directory -Path $packagingDir
          New-Item -ItemType directory -Path $packagingDir/red4ext
          New-Item -ItemType directory -Path $packagingDir/red4ext/plugins
          New-Item -ItemType directory -Path $packagingDir/red4ext/plugins/RED4ext.RTTIDumper

          # Copy the PDBs.
          Copy-Item -Path ./${{ matrix.config }}/bin/RED4ext.RTTIDumper.pdb -Destination $packagingDir/red4ext/plugins/RED4ext.RTTIDumper

      - name: Upload ZIP
        uses: actions/upload-artifact@v3
        with:
          name: red4_rttidumper_${{ env.RTTIDUMPER_PRETTY_CONFIG }}_${{ env.RTTIDUMPER_COMMIT_SHA }}
          path: build/.packaging/

      - name: Upload ZIP (PDBs)
        uses: actions/upload-artifact@v3
        with:
          name: red4_rttidumper_${{ env.RTTIDUMPER_PRETTY_CONFIG }}_${{ env.RTTIDUMPER_COMMIT_SHA }}_pdbs
          path: build/.packaging_pdbs/
